### ISSUE TITLE
python 3.7.9 run test.py No module named 'torch.vision'

### ISSUE THREAD

**Issue by thinkdb** [abhishekyana/CycleGANs-PyTorch#2]
Hi:
I run test.py and encounter an error. error message is  

python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from datasets import AnBDataset
  File "/Users/think/app/CycleGANs-PyTorch/datasets.py", line 2, in <module>
    import torch.vision.transforms as transforms
ModuleNotFoundError: No module named 'torch.vision'

My steps are as follows:
1. clone CycleGANs-PyTorch
2. conda create --name old2young python=3.7 and activate old2young
3. pip install -r requirements.txt
4. run test.py

Result of step 3：
pip install -r requirements.txt
Requirement already satisfied: numpy==1.16.2 in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.16.2)
Requirement already satisfied: torch==1.1.0 in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: scipy==1.2.1 in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (1.2.1)
Requirement already satisfied: torchvision==0.3.0 in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (0.3.0)
Requirement already satisfied: visdom==0.1.8.8 in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (0.1.8.8)
Requirement already satisfied: Pillow==6.1.0 in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (6.1.0)
Requirement already satisfied: six in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from torchvision==0.3.0->-r requirements.txt (line 4)) (1.15.0)
Requirement already satisfied: requests in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from visdom==0.1.8.8->-r requirements.txt (line 5)) (2.25.0)
Requirement already satisfied: tornado in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from visdom==0.1.8.8->-r requirements.txt (line 5)) (6.1)
Requirement already satisfied: pyzmq in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from visdom==0.1.8.8->-r requirements.txt (line 5)) (20.0.0)
Requirement already satisfied: torchfile in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from visdom==0.1.8.8->-r requirements.txt (line 5)) (0.1.0)
Requirement already satisfied: websocket-client in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from visdom==0.1.8.8->-r requirements.txt (line 5)) (0.57.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from requests->visdom==0.1.8.8->-r requirements.txt (line 5)) (2020.6.20)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from requests->visdom==0.1.8.8->-r requirements.txt (line 5)) (1.26.2)
Requirement already satisfied: idna<3,>=2.5 in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from requests->visdom==0.1.8.8->-r requirements.txt (line 5)) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/think/miniconda3/envs/old2young/lib/python3.7/site-packages (from requests->visdom==0.1.8.8->-r requirements.txt (line 5)) (3.0.4)

**Comment by thinkdb** [comment]
The problem is solved
